'user strict';

var moduleController = angular.module('app.controllers', []);

moduleController.controller("LoginCtrl", require('./controllers/LoginCtrl'));
moduleController.controller("HeaderCtrl", require('./controllers/HeaderCtrl'));
moduleController.controller("BoarderCtrl", require('./controllers/BoarderCtrl'));
moduleController.controller("MenuCtrl", require('./controllers/MenuCtrl'));
moduleController.controller("MealCtrl", require('./controllers/Meal/MealCtrl'));
moduleController.controller("AddMealCtrl", require('./controllers/Meal/AddMealCtrl'));
moduleController.controller("SwaddleCtrl", require('./controllers/SwaddleCtrl'));
moduleController.controller("AddSwaddleCtrl", require('./controllers/AddSwaddleCtrl'));
moduleController.controller("InsulinDosageCtrl", require('./controllers/InsulinDosageCtrl'));
moduleController.controller("AddInsulinDosageCtrl", require('./controllers/AddInsulinDosageCtrl'));
moduleController.controller("ObservationCtrl", require('./controllers/ObservationCtrl'));
moduleController.controller("AddObservationCtrl", require('./controllers/AddObservationCtrl'));
moduleController.controller("PatchCtrl", require('./controllers/PatchCtrl'));
moduleController.controller("AddPatchCtrl", require('./controllers/AddPatchCtrl'));
moduleController.controller("AerosolCtrl", require('./controllers/Aerosol/AerosolCtrl'));
moduleController.controller("AddAerosolCtrl", require('./controllers/Aerosol/AddAerosolCtrl'));
moduleController.controller("UpdateAerosolCtrl", require('./controllers/Aerosol/UpdateAerosolCtrl'));
moduleController.controller("WoundCtrl", require('./controllers/WoundCtrl'));
moduleController.controller("AddWoundCtrl", require('./controllers/AddWoundCtrl'));
moduleController.controller("DrugTreatmentCtrl", require('./controllers/DrugTreatement/DrugTreatmentCtrl'));
moduleController.controller("AddDrugTreatmentCtrl", require('./controllers/DrugTreatement/AddDrugTreatmentCtrl'));
moduleController.controller("InsulinTakingCtrl", require('./controllers/InsulinTakingCtrl'));
moduleController.controller("AddInsulinTakingCtrl", require('./controllers/AddInsulinTakingCtrl'));
moduleController.controller("TherapeuticCtrl", require('./controllers/TherapeuticCtrl'));
moduleController.controller("AddTherapeuticCtrl", require('./controllers/AddTherapeuticCtrl'));
moduleController.controller("InjectionCtrl", require('./controllers/InjectionCtrl'));
moduleController.controller("AddInjectionCtrl", require('./controllers/AddInjectionCtrl'));
moduleController.controller("HygieneCtrl", require('./controllers/Hygiene/HygieneCtrl'));
moduleController.controller("AddHygieneCtrl", require('./controllers/Hygiene/AddHygieneCtrl'));
moduleController.controller("ClothingCtrl", require('./controllers/Clothing/ClothingCtrl'));
moduleController.controller("AddClothingCtrl", require('./controllers/Clothing/AddClothingCtrl'));
moduleController.controller("MobilizationCtrl", require('./controllers/MobilizationCtrl'));
moduleController.controller("AddMobilizationCtrl", require('./controllers/AddMobilizationCtrl'));
moduleController.controller("ToiletHelpingCtrl", require('./controllers/ToiletHelpingCtrl'));
moduleController.controller("AddToiletHelpingCtrl", require('./controllers/AddToiletHelpingCtrl'));
moduleController.controller("IncontinenceCtrl", require('./controllers/IncontinenceCtrl'));
moduleController.controller("AddIncontinenceCtrl", require('./controllers/AddIncontinenceCtrl'));
moduleController.controller("EatCtrl", require('./controllers/Eat/EatCtrl'));
moduleController.controller("AddEatCtrl", require('./controllers/Eat/AddEatCtrl'));
moduleController.controller("ParameterCtrl", require('./controllers/ParameterCtrl'));
moduleController.controller("AddParameterCtrl", require('./controllers/AddParameterCtrl'));
moduleController.controller("DisorderCtrl", require('./controllers/Disorder/DisorderCtrl'));
moduleController.controller("AddDisorderCtrl", require('./controllers/Disorder/AddDisorderCtrl'));

